apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shortlink.fullname" . }}-config
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
data:
  # Non-sensitive configuration
  LOG_LEVEL: {{ .Values.api.env.LOG_LEVEL | quote }}
  SLUG_LENGTH: {{ .Values.api.env.SLUG_LENGTH | quote }}
  BASE_URL: {{ .Values.api.env.BASE_URL | quote }}
