apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortlink.fullname" . }}-postgres
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "shortlink.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
