apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortlink.fullname" . }}-web
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "shortlink.webSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
