apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortlink.fullname" . }}-api
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "shortlink.apiSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: http
    - name: metrics
      port: {{ .Values.api.metricsPort }}
      targetPort: metrics
